"""empty message

Revision ID: c8fc7b0dae4a
Revises: d50e25a217ac
Create Date: 2025-01-07 15:11:21.409065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8fc7b0dae4a'
down_revision = 'd50e25a217ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('population', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Planet', schema=None) as batch_op:
        batch_op.drop_column('population')

    # ### end Alembic commands ###
