"""empty message

Revision ID: d50e25a217ac
Revises: 28676f219680
Create Date: 2025-01-07 15:05:28.166293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd50e25a217ac'
down_revision = '28676f219680'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=120), nullable=True))
        batch_op.drop_constraint('Planet_climate_key', type_='unique')
        batch_op.create_unique_constraint(None, ['description'])
        batch_op.drop_column('climate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('climate', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('Planet_climate_key', ['climate'])
        batch_op.drop_column('description')

    # ### end Alembic commands ###
